#!/usr/bin/python3
#SPDX-FileCopyrightText: 2023 kouzou2111
#SPDX-License-Identifier: BSD-3-clause

import sys

ans = 0

for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)
